# Generated by Django 3.2.9 on 2022-03-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wca',
            options={'verbose_name_plural': 'WCA'},
        ),
    ]
