# Generated by Django 3.2.9 on 2022-03-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_account_name'),
        ('product', '0002_alter_wca_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wca',
            name='isin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.identifier'),
        ),
    ]
