# Generated by Django 3.2.9 on 2022-03-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_wca_isin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wca',
            old_name='isin',
            new_name='code',
        ),
    ]
