# Generated by Django 3.2.9 on 2022-03-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_isin_wca_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wca',
            old_name='code',
            new_name='isin',
        ),
    ]
