# Generated by Django 3.2.9 on 2022-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_code_wca_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wca',
            name='isin',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
