# Generated by Django 3.2.9 on 2022-03-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_wca_isin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WCA',
        ),
    ]
