# Generated by Django 3.2.9 on 2022-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='desc',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
