# Generated by Django 3.2.9 on 2021-12-19 10:03

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211219_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='account.office'),
        ),
    ]
