# Generated by Django 3.2.9 on 2021-12-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='company_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.companyrole'),
        ),
    ]
