# Generated by Django 3.2.9 on 2022-01-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.companyrole'),
        ),
    ]
