# Generated by Django 3.2.9 on 2022-01-03 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, max_length=500, verbose_name='comments')),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('initial_count', models.IntegerField(blank=True, null=True)),
                ('update_count', models.IntegerField(blank=True, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('identifier_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.identifiertype')),
                ('priority_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.prioritytype')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
