# Generated by Django 3.2.9 on 2022-01-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='USCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('account_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.account')),
            ],
        ),
        migrations.CreateModel(
            name='ISIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('account_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.account')),
            ],
        ),
    ]
