# Generated by Django 3.2.9 on 2022-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220103_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='changed_date',
            new_name='acttime',
        ),
        migrations.AddField(
            model_name='account',
            name='actflag',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='isin',
            name='actflag',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='isin',
            name='acttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uscode',
            name='actflag',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='uscode',
            name='acttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
