# Generated by Django 3.2.9 on 2022-01-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_account_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isin',
            old_name='account_name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='uscode',
            old_name='account_name',
            new_name='account',
        ),
    ]
