# Generated by Django 3.2.9 on 2022-01-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220111_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acttime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='isin',
            name='acttime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uscode',
            name='acttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
