# Generated by Django 3.2.9 on 2022-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220111_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isin',
            name='acttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uscode',
            name='acttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
