# Generated by Django 3.2.9 on 2022-01-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0010_alter_account_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identifier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.identifiertype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='priority_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.prioritytype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
