# Generated by Django 3.2.9 on 2022-01-11 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_account_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acttime',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='isin',
            name='acttime',
        ),
        migrations.RemoveField(
            model_name='uscode',
            name='acttime',
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='isin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isin',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uscode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uscode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
