# Generated by Django 3.2.9 on 2022-01-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220111_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isin',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='uscode',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.account'),
        ),
    ]
