# Generated by Django 3.2.9 on 2022-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20220114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='isin',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='uscode',
            name='code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
