# Generated by Django 3.2.9 on 2022-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20220114_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='isin',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='uscode',
            name='code',
            field=models.CharField(max_length=9),
        ),
    ]
