# Generated by Django 3.2.9 on 2022-02-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20220114_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='identifier_type',
        ),
    ]
