# Generated by Django 3.2.9 on 2022-02-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='identifier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.identifiertype'),
        ),
    ]
