# Generated by Django 3.2.9 on 2022-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_identifier_identifier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
