# Generated by Django 3.2.9 on 2022-02-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20220215_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifier',
            old_name='identifier_type',
            new_name='type',
        ),
    ]
