# Generated by Django 3.2.9 on 2022-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_identifier_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
