# Generated by Django 3.2.9 on 2022-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_account_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.TextField(blank=True, max_length=50, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
