# Generated by Django 3.2.9 on 2022-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_account_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.TextField(blank=True, max_length=50, verbose_name='comments'),
        ),
    ]
