# Generated by Django 3.2.9 on 2022-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_auto_20220307_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
