# Generated by Django 3.2.9 on 2022-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='user',
        ),
    ]
