# Generated by Django 3.2.9 on 2022-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_rename_username_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='deadline_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='initial_count',
            new_name='initial',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='invalid_count',
            new_name='invalid',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='priority_type',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='total_count',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='update_count',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='valid_count',
            new_name='valid',
        ),
    ]
